server:
  port: 8030
spring:
  application:
    name: dom-product-service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/dom-product
    username: postgres
    password: 205015
  rabbitmq:
    addresses: amqps://qkpfixxq:RKmkHq2hoXRzFS9UHlMQD3_gCo_0bAXn@chimpanzee.rmq.cloudamqp.com/qkpfixxq
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    web: debug
    com.coralsoft: debug

dom:
  api:
    url:
      order: 'http://localhost:8070'
  broker:
    exchange:
      productService: dom.productservice