server:
  port: 8030
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/dom-product
    username: postgres
    password: 205015
logging:
  level:
    web: debug
    com.coralsoft: debug